export const TAGS = {
  SOFTWARE: 'software',
  DATA: 'data',
  AI: 'ai',
  UX: 'ux',
  MARKETING: 'marketing',
  FINANCE: 'finance',
  ACCOUNTING: 'accounting',
  PUBLIC: 'public',
  LAW: 'law',
  MEDIA: 'media',
  CONTENTS: 'contents',
  ENGINEERING: 'engineering',
  SEMICONDUCTOR: 'semiconductor',
  BIO: 'bio',
  ENERGY: 'energy',
  FOOD: 'food',
  DESIGN: 'design',
  EDUCATION: 'education',
  RESEARCH: 'research',
  LANGUAGE: 'language',
  GLOBAL: 'global',
  MANAGEMENT: 'management',
  CERTIFICATE: 'certificate',
  COMPETITION: 'competition',
  INTERNSHIP: 'internship',
  ACTIVITY: 'activity',
  PROJECT: 'project',
  STARTUP: 'startup',
  NCS: 'ncs',
};

export const TAG_LABELS = {
  [TAGS.SOFTWARE]: '소프트웨어',
  [TAGS.DATA]: '데이터',
  [TAGS.AI]: 'AI',
  [TAGS.UX]: 'UX',
  [TAGS.MARKETING]: '마케팅',
  [TAGS.FINANCE]: '금융',
  [TAGS.ACCOUNTING]: '회계',
  [TAGS.PUBLIC]: '공공',
  [TAGS.LAW]: '법무',
  [TAGS.MEDIA]: '미디어',
  [TAGS.CONTENTS]: '콘텐츠',
  [TAGS.ENGINEERING]: '공학',
  [TAGS.SEMICONDUCTOR]: '반도체',
  [TAGS.BIO]: '바이오',
  [TAGS.ENERGY]: '에너지',
  [TAGS.FOOD]: '식품',
  [TAGS.DESIGN]: '디자인',
  [TAGS.EDUCATION]: '교육',
  [TAGS.RESEARCH]: '연구',
  [TAGS.LANGUAGE]: '어학',
  [TAGS.GLOBAL]: '글로벌',
  [TAGS.MANAGEMENT]: '경영',
  [TAGS.CERTIFICATE]: '자격증',
  [TAGS.COMPETITION]: '공모전',
  [TAGS.INTERNSHIP]: '인턴',
  [TAGS.ACTIVITY]: '대외활동',
  [TAGS.PROJECT]: '프로젝트',
  [TAGS.STARTUP]: '창업',
  [TAGS.NCS]: 'NCS',
};

const W = TAGS;

export const MAJOR_TAG_WEIGHTS = {
  '컴퓨터소프트웨어학부': { [W.SOFTWARE]: 10, [W.DATA]: 8, [W.AI]: 8, [W.ENGINEERING]: 5, [W.STARTUP]: 3 },
  '소프트웨어학부': { [W.SOFTWARE]: 10, [W.DATA]: 8, [W.AI]: 8, [W.ENGINEERING]: 5 },
  '인공지능학과': { [W.AI]: 10, [W.DATA]: 9, [W.SOFTWARE]: 8, [W.RESEARCH]: 5 },
  '데이터사이언스전공': { [W.DATA]: 10, [W.AI]: 8, [W.SOFTWARE]: 7, [W.RESEARCH]: 4 },
  '정보시스템학과': { [W.SOFTWARE]: 7, [W.DATA]: 7, [W.MANAGEMENT]: 8, [W.UX]: 5 },
  '산업공학과': { [W.DATA]: 8, [W.MANAGEMENT]: 8, [W.ENGINEERING]: 7, [W.AI]: 5 },
  '융합전자공학부': { [W.ENGINEERING]: 9, [W.SEMICONDUCTOR]: 8, [W.SOFTWARE]: 5, [W.AI]: 4 },
  '전자공학부': { [W.ENGINEERING]: 9, [W.SEMICONDUCTOR]: 8, [W.SOFTWARE]: 5, [W.AI]: 4 },
  '전기공학전공': { [W.ENGINEERING]: 9, [W.ENERGY]: 7, [W.SEMICONDUCTOR]: 5 },
  '기계공학부': { [W.ENGINEERING]: 10, [W.SEMICONDUCTOR]: 5, [W.ENERGY]: 5, [W.RESEARCH]: 4 },
  '기계공학과': { [W.ENGINEERING]: 10, [W.SEMICONDUCTOR]: 5, [W.ENERGY]: 5, [W.RESEARCH]: 4 },
  '화학공학과': { [W.ENGINEERING]: 8, [W.BIO]: 6, [W.ENERGY]: 6, [W.SEMICONDUCTOR]: 4 },
  '신소재공학부': { [W.ENGINEERING]: 8, [W.SEMICONDUCTOR]: 7, [W.ENERGY]: 5, [W.RESEARCH]: 4 },
  '생명공학과': { [W.BIO]: 10, [W.RESEARCH]: 7, [W.DATA]: 4, [W.ENGINEERING]: 4 },
  '식품영양학과': { [W.FOOD]: 10, [W.BIO]: 6, [W.RESEARCH]: 5, [W.CERTIFICATE]: 4 },
  '경제금융학부': { [W.FINANCE]: 10, [W.DATA]: 6, [W.ACCOUNTING]: 5, [W.MANAGEMENT]: 4 },
  '경영학부': { [W.MANAGEMENT]: 10, [W.MARKETING]: 7, [W.FINANCE]: 6, [W.ACCOUNTING]: 5 },
  '파이낸스경영학과': { [W.FINANCE]: 10, [W.ACCOUNTING]: 8, [W.DATA]: 5, [W.MANAGEMENT]: 5 },
  '회계세무학과': { [W.ACCOUNTING]: 10, [W.FINANCE]: 7, [W.CERTIFICATE]: 6 },
  '정책학과': { [W.PUBLIC]: 9, [W.LAW]: 6, [W.MANAGEMENT]: 5, [W.DATA]: 3 },
  '행정학과': { [W.PUBLIC]: 10, [W.LAW]: 5, [W.NCS]: 5, [W.MANAGEMENT]: 4 },
  '미디어커뮤니케이션학과': { [W.MEDIA]: 10, [W.CONTENTS]: 8, [W.MARKETING]: 6, [W.LANGUAGE]: 3 },
  '광고홍보학과': { [W.MARKETING]: 10, [W.CONTENTS]: 7, [W.MEDIA]: 6, [W.DATA]: 4 },
  '문화콘텐츠학과': { [W.CONTENTS]: 10, [W.MEDIA]: 7, [W.DESIGN]: 4, [W.MARKETING]: 4 },
  '국어국문학과': { [W.CONTENTS]: 7, [W.MEDIA]: 6, [W.EDUCATION]: 5, [W.LANGUAGE]: 5 },
  '영어영문학과': { [W.LANGUAGE]: 10, [W.GLOBAL]: 7, [W.CONTENTS]: 5, [W.EDUCATION]: 4 },
  '영어교육과': { [W.EDUCATION]: 10, [W.LANGUAGE]: 8, [W.GLOBAL]: 5 },
  '교육학과': { [W.EDUCATION]: 10, [W.PUBLIC]: 4, [W.CONTENTS]: 4 },
  '응용미술교육과': { [W.DESIGN]: 8, [W.EDUCATION]: 8, [W.CONTENTS]: 4 },
  '의류학과': { [W.DESIGN]: 9, [W.MARKETING]: 6, [W.GLOBAL]: 4, [W.CONTENTS]: 4 },
  '영상디자인학과': { [W.DESIGN]: 10, [W.CONTENTS]: 8, [W.MEDIA]: 7, [W.AI]: 4 },
  '융합디자인학부': { [W.DESIGN]: 10, [W.UX]: 7, [W.CONTENTS]: 5, [W.SOFTWARE]: 3 },
  '간호학과': { [W.BIO]: 7, [W.PUBLIC]: 5, [W.CERTIFICATE]: 5, [W.RESEARCH]: 4 },
};

export const COLLEGE_TAG_WEIGHTS = {
  '공과대학': { [W.ENGINEERING]: 5, [W.SOFTWARE]: 3, [W.RESEARCH]: 3 },
  '공학대학': { [W.ENGINEERING]: 5, [W.SOFTWARE]: 3, [W.RESEARCH]: 3 },
  '소프트웨어융합대학': { [W.SOFTWARE]: 6, [W.DATA]: 4, [W.AI]: 4 },
  '경영대학': { [W.MANAGEMENT]: 5, [W.MARKETING]: 3, [W.FINANCE]: 3 },
  '경상대학': { [W.MANAGEMENT]: 5, [W.FINANCE]: 4, [W.ACCOUNTING]: 3 },
  '경제금융대학': { [W.FINANCE]: 6, [W.DATA]: 3 },
  '정책과학대학': { [W.PUBLIC]: 5, [W.LAW]: 3 },
  '사회과학대학': { [W.MEDIA]: 3, [W.PUBLIC]: 3, [W.MARKETING]: 3 },
  '커뮤니케이션&컬처대학': { [W.MEDIA]: 5, [W.CONTENTS]: 5, [W.MARKETING]: 3 },
  '디자인대학': { [W.DESIGN]: 6, [W.CONTENTS]: 4, [W.UX]: 3 },
  '사범대학': { [W.EDUCATION]: 6, [W.LANGUAGE]: 3 },
  '생활과학대학': { [W.FOOD]: 4, [W.DESIGN]: 4, [W.BIO]: 3 },
  '국제학부': { [W.GLOBAL]: 6, [W.LANGUAGE]: 4, [W.MANAGEMENT]: 3 },
};

export const CAREER_TAG_WEIGHTS = {
  '프론트엔드개발자': { [W.SOFTWARE]: 10, [W.UX]: 6, [W.PROJECT]: 5, [W.COMPETITION]: 4 },
  '백엔드개발자': { [W.SOFTWARE]: 10, [W.DATA]: 6, [W.PROJECT]: 5, [W.CERTIFICATE]: 4 },
  '앱개발자': { [W.SOFTWARE]: 10, [W.UX]: 4, [W.PROJECT]: 5 },
  '게임개발자': { [W.SOFTWARE]: 9, [W.CONTENTS]: 5, [W.COMPETITION]: 5 },
  '소프트웨어개발자': { [W.SOFTWARE]: 10, [W.DATA]: 5, [W.PROJECT]: 5 },
  '데이터사이언티스트': { [W.DATA]: 10, [W.AI]: 8, [W.RESEARCH]: 5, [W.PROJECT]: 4 },
  '데이터분석가': { [W.DATA]: 10, [W.MARKETING]: 4, [W.FINANCE]: 4, [W.CERTIFICATE]: 5 },
  '데이터엔지니어': { [W.DATA]: 10, [W.SOFTWARE]: 7, [W.CERTIFICATE]: 4 },
  'AI/ML엔지니어': { [W.AI]: 10, [W.DATA]: 8, [W.SOFTWARE]: 6, [W.RESEARCH]: 5 },
  'AI/ML연구원': { [W.AI]: 10, [W.RESEARCH]: 8, [W.DATA]: 6 },
  'MLOps엔지니어': { [W.AI]: 8, [W.SOFTWARE]: 8, [W.DATA]: 7 },
  '프롬프트엔지니어': { [W.AI]: 8, [W.CONTENTS]: 6, [W.SOFTWARE]: 4 },
  '클라우드엔지니어': { [W.SOFTWARE]: 8, [W.ENGINEERING]: 5, [W.CERTIFICATE]: 6 },
  '보안엔지니어': { [W.SOFTWARE]: 8, [W.CERTIFICATE]: 6, [W.ENGINEERING]: 4 },
  'IT컨설턴트': { [W.SOFTWARE]: 6, [W.MANAGEMENT]: 8, [W.DATA]: 5 },
  '서비스기획자(PM·PO)': { [W.MANAGEMENT]: 9, [W.UX]: 7, [W.DATA]: 6, [W.SOFTWARE]: 4 },
  '웹기획자': { [W.UX]: 8, [W.MANAGEMENT]: 7, [W.SOFTWARE]: 4 },
  '경영·비즈니스기획': { [W.MANAGEMENT]: 10, [W.DATA]: 5, [W.MARKETING]: 4 },
  'AI기획자': { [W.AI]: 8, [W.MANAGEMENT]: 8, [W.DATA]: 6 },
  'AI사업전략': { [W.AI]: 7, [W.MANAGEMENT]: 9, [W.DATA]: 5 },
  '컨설턴트': { [W.MANAGEMENT]: 9, [W.DATA]: 6, [W.FINANCE]: 4 },
  '브랜드마케터': { [W.MARKETING]: 10, [W.CONTENTS]: 6, [W.MANAGEMENT]: 5 },
  '퍼포먼스마케터': { [W.MARKETING]: 10, [W.DATA]: 7, [W.CERTIFICATE]: 4 },
  '콘텐츠마케터': { [W.MARKETING]: 9, [W.CONTENTS]: 8, [W.MEDIA]: 5 },
  'CRM마케터': { [W.MARKETING]: 9, [W.DATA]: 7, [W.MANAGEMENT]: 4 },
  '그로스해커': { [W.MARKETING]: 8, [W.DATA]: 8, [W.SOFTWARE]: 4 },
  '홍보(PR)': { [W.MARKETING]: 8, [W.MEDIA]: 7, [W.CONTENTS]: 5 },
  'AE(광고기획자)': { [W.MARKETING]: 9, [W.CONTENTS]: 7, [W.MEDIA]: 5 },
  '카피라이터': { [W.CONTENTS]: 9, [W.MARKETING]: 6, [W.MEDIA]: 5 },
  'MD': { [W.MARKETING]: 8, [W.MANAGEMENT]: 7, [W.DATA]: 4 },
  'UI·UX디자이너': { [W.UX]: 10, [W.DESIGN]: 9, [W.SOFTWARE]: 4, [W.PROJECT]: 4 },
  '웹디자이너': { [W.DESIGN]: 9, [W.UX]: 8, [W.SOFTWARE]: 4 },
  '영상디자이너': { [W.DESIGN]: 9, [W.MEDIA]: 8, [W.CONTENTS]: 7 },
  '그래픽디자이너': { [W.DESIGN]: 10, [W.CONTENTS]: 5 },
  '패션디자이너': { [W.DESIGN]: 10, [W.GLOBAL]: 5, [W.MARKETING]: 4 },
  '회계사(CPA)': { [W.ACCOUNTING]: 10, [W.FINANCE]: 6, [W.CERTIFICATE]: 8 },
  '세무사': { [W.ACCOUNTING]: 10, [W.CERTIFICATE]: 8 },
  '회계담당자': { [W.ACCOUNTING]: 9, [W.FINANCE]: 5, [W.CERTIFICATE]: 5 },
  '재무담당자': { [W.FINANCE]: 9, [W.ACCOUNTING]: 6, [W.DATA]: 4 },
  '애널리스트': { [W.FINANCE]: 10, [W.DATA]: 7, [W.RESEARCH]: 5 },
  '펀드매니저': { [W.FINANCE]: 10, [W.DATA]: 5, [W.GLOBAL]: 4 },
  '은행원·텔러(IB/PB 등)': { [W.FINANCE]: 10, [W.CERTIFICATE]: 6, [W.LANGUAGE]: 4 },
  '반도체엔지니어': { [W.SEMICONDUCTOR]: 10, [W.ENGINEERING]: 8, [W.RESEARCH]: 5, [W.INTERNSHIP]: 5 },
  '공정엔지니어': { [W.ENGINEERING]: 9, [W.SEMICONDUCTOR]: 7, [W.CERTIFICATE]: 4 },
  '전기·전자엔지니어': { [W.ENGINEERING]: 10, [W.SEMICONDUCTOR]: 6, [W.CERTIFICATE]: 5 },
  '기계엔지니어': { [W.ENGINEERING]: 10, [W.CERTIFICATE]: 6, [W.INTERNSHIP]: 4 },
  '화학엔지니어': { [W.ENGINEERING]: 9, [W.BIO]: 4, [W.CERTIFICATE]: 5 },
  'R&D·연구원': { [W.RESEARCH]: 10, [W.ENGINEERING]: 6, [W.BIO]: 4, [W.AI]: 3 },
  '품질관리자(QA/QC)': { [W.ENGINEERING]: 7, [W.CERTIFICATE]: 6, [W.FOOD]: 4 },
  '변호사(로스쿨)': { [W.LAW]: 10, [W.LANGUAGE]: 5, [W.PUBLIC]: 4 },
  '법무담당자': { [W.LAW]: 9, [W.MANAGEMENT]: 4, [W.CERTIFICATE]: 4 },
  '공기업(NCS 준비)': { [W.PUBLIC]: 10, [W.NCS]: 8, [W.CERTIFICATE]: 6, [W.LANGUAGE]: 4 },
  '5급 행정고시': { [W.PUBLIC]: 10, [W.LAW]: 5, [W.CERTIFICATE]: 5 },
  '5급 기술고시': { [W.PUBLIC]: 8, [W.ENGINEERING]: 7, [W.CERTIFICATE]: 5 },
  '사회복지사': { [W.PUBLIC]: 7, [W.EDUCATION]: 5, [W.CERTIFICATE]: 5 },
  'PD·감독': { [W.MEDIA]: 10, [W.CONTENTS]: 8, [W.PROJECT]: 4 },
  '기자': { [W.MEDIA]: 10, [W.LANGUAGE]: 6, [W.CONTENTS]: 6 },
  '아나운서': { [W.MEDIA]: 9, [W.LANGUAGE]: 8 },
  '콘텐츠에디터': { [W.CONTENTS]: 10, [W.MEDIA]: 7, [W.MARKETING]: 5 },
  '작가': { [W.CONTENTS]: 10, [W.LANGUAGE]: 5 },
  '영상편집자': { [W.MEDIA]: 8, [W.CONTENTS]: 8, [W.DESIGN]: 5 },
  'AI콘텐츠크리에이터': { [W.AI]: 7, [W.CONTENTS]: 9, [W.DESIGN]: 5 },
  '통번역사': { [W.LANGUAGE]: 10, [W.GLOBAL]: 8 },
  '해외영업': { [W.GLOBAL]: 9, [W.LANGUAGE]: 7, [W.MANAGEMENT]: 5 },
  '물류관리자': { [W.MANAGEMENT]: 7, [W.GLOBAL]: 5, [W.CERTIFICATE]: 5 },
  '인사담당자': { [W.MANAGEMENT]: 8, [W.EDUCATION]: 5, [W.PUBLIC]: 3 },
  '건축기사': { [W.ENGINEERING]: 8, [W.CERTIFICATE]: 8, [W.DESIGN]: 4 },
  '환경기사': { [W.ENGINEERING]: 7, [W.BIO]: 5, [W.CERTIFICATE]: 7 },
  '바이오·제약연구원': { [W.BIO]: 10, [W.RESEARCH]: 8, [W.DATA]: 4 },
  '임상연구원(CRA)': { [W.BIO]: 9, [W.RESEARCH]: 6, [W.CERTIFICATE]: 4 },
  '영양사': { [W.FOOD]: 9, [W.BIO]: 5, [W.CERTIFICATE]: 7 },
  '식품연구원': { [W.FOOD]: 10, [W.BIO]: 6, [W.RESEARCH]: 6 },
};

export const CAREER_CATEGORY_TAG_WEIGHTS = {
  'IT·AI·데이터': { [W.SOFTWARE]: 7, [W.DATA]: 6, [W.AI]: 6 },
  '기획·마케팅·광고': { [W.MARKETING]: 7, [W.MANAGEMENT]: 5, [W.CONTENTS]: 4 },
  '디자인': { [W.DESIGN]: 8, [W.UX]: 5, [W.CONTENTS]: 4 },
  '금융·재무·회계': { [W.FINANCE]: 7, [W.ACCOUNTING]: 6, [W.DATA]: 4 },
  '엔지니어링·제조': { [W.ENGINEERING]: 8, [W.SEMICONDUCTOR]: 4, [W.RESEARCH]: 4 },
  '전문직·공직·법무': { [W.PUBLIC]: 6, [W.LAW]: 6, [W.CERTIFICATE]: 4 },
  '미디어·문화·콘텐츠': { [W.MEDIA]: 7, [W.CONTENTS]: 7, [W.LANGUAGE]: 3 },
  '물류·무역·영업·HR': { [W.MANAGEMENT]: 6, [W.GLOBAL]: 5, [W.LANGUAGE]: 3 },
  '건축·환경·의료·바이오': { [W.ENGINEERING]: 5, [W.BIO]: 5, [W.FOOD]: 4 },
};

export const GRADE_TAG_WEIGHTS = {
  1: { [W.LANGUAGE]: 5, [W.ACTIVITY]: 4, [W.PROJECT]: 2, [W.CERTIFICATE]: 2 },
  2: { [W.CERTIFICATE]: 5, [W.ACTIVITY]: 5, [W.PROJECT]: 4, [W.COMPETITION]: 3 },
  3: { [W.INTERNSHIP]: 6, [W.COMPETITION]: 5, [W.PROJECT]: 5, [W.CERTIFICATE]: 4 },
  4: { [W.INTERNSHIP]: 8, [W.CERTIFICATE]: 4, [W.PROJECT]: 4, [W.LANGUAGE]: 3 },
};

export const ACTIVITIES = [
  { id: 'toeic', title: 'TOEIC', cat: 'lang', targetScore: '850', type: 'language', tags: [W.LANGUAGE, W.GLOBAL, W.CERTIFICATE], baseWeight: 7, recommendedGrades: [1, 2], source: 'YBM', targetDate: '2026-06-14', duration: '2~3개월', desc: '대부분의 직무에서 기본 정량 스펙으로 활용되는 어학 점수입니다.', url: 'https://exam.toeic.co.kr/' },
  { id: 'opic', title: 'OPIc', cat: 'lang', targetScore: 'IM2', type: 'language', tags: [W.LANGUAGE, W.GLOBAL, W.CERTIFICATE], baseWeight: 7, recommendedGrades: [2, 3], source: 'OPIc', targetDate: '2026-06-25', duration: '1~2개월', desc: '대기업과 글로벌 직무에서 커뮤니케이션 역량을 보여주는 대표 어학 스펙입니다.', url: 'https://www.opic.or.kr/' },
  { id: 'kbs', title: 'KBS한국어능력시험', cat: 'lang', targetScore: '2+', type: 'language', tags: [W.LANGUAGE, W.MEDIA, W.LAW, W.CERTIFICATE], baseWeight: 6, recommendedGrades: [1, 2, 3], source: 'KBS', targetDate: '2026-08-16', duration: '1~2개월', desc: '언론, 법무, 공공 계열에서 글쓰기와 언어 감각을 보완합니다.', url: 'http://www.klt.or.kr/' },
  { id: 'sqld', title: 'SQLD', cat: 'cert', type: 'certificate', tags: [W.DATA, W.SOFTWARE, W.CERTIFICATE], baseWeight: 8, recommendedGrades: [2, 3], source: '데이터자격검정', targetDate: '2026-08-24', duration: '1~2개월', desc: '데이터 분석, 백엔드, 기획 직무에서 데이터베이스 기초 역량을 증명합니다.', url: 'https://www.dataq.or.kr/' },
  { id: 'adsp', title: 'ADsP', cat: 'cert', type: 'certificate', tags: [W.DATA, W.AI, W.MARKETING, W.FINANCE, W.CERTIFICATE], baseWeight: 8, recommendedGrades: [2, 3], source: '데이터자격검정', targetDate: '2026-08-24', duration: '1~2개월', desc: '데이터 기반 의사결정이 필요한 분석, 마케팅, 금융 직무에 잘 맞습니다.', url: 'https://www.dataq.or.kr/' },
  { id: 'engineer-it', title: '정보처리기사', cat: 'cert', type: 'certificate', tags: [W.SOFTWARE, W.ENGINEERING, W.CERTIFICATE], baseWeight: 8, recommendedGrades: [3, 4], source: 'Q-Net', targetDate: '2026-07-05', duration: '2~3개월', desc: '소프트웨어 개발과 IT 직무의 전공 기초를 공인 자격으로 보여줍니다.', url: 'https://www.q-net.or.kr/' },
  { id: 'com-1', title: '컴퓨터활용능력 1급', cat: 'cert', type: 'certificate', tags: [W.CERTIFICATE, W.PUBLIC, W.NCS, W.DATA, W.MANAGEMENT], baseWeight: 7, recommendedGrades: [1, 2], source: '대한상공회의소', targetDate: '2026-06-10', duration: '1~2개월', desc: '공기업, 사무, 기획 직무에서 기본 업무 툴 역량을 보완합니다.', url: 'https://license.korcham.net/' },
  { id: 'history', title: '한국사능력검정시험', cat: 'cert', type: 'certificate', tags: [W.PUBLIC, W.NCS, W.CERTIFICATE], baseWeight: 7, recommendedGrades: [1, 2], source: '국사편찬위원회', targetDate: '2026-08-08', duration: '1개월', desc: '공기업과 공직 준비에서 자주 요구되는 기본 가산점 자격입니다.', url: 'https://www.historyexam.go.kr/' },
  { id: 'ga4', title: 'GA4', cat: 'cert', type: 'certificate', tags: [W.MARKETING, W.DATA, W.CERTIFICATE], baseWeight: 7, recommendedGrades: [2, 3], source: 'Google Skillshop', targetDate: '2026-07-15', duration: '2~4주', desc: '퍼포먼스 마케팅과 서비스 기획에서 데이터 분석 감각을 보여줍니다.', url: 'https://skillshop.exceedlms.com/' },
  { id: 'afpk', title: 'AFPK', cat: 'cert', type: 'certificate', tags: [W.FINANCE, W.CERTIFICATE], baseWeight: 8, recommendedGrades: [2, 3], source: '한국FPSB', targetDate: '2026-07-25', duration: '2~3개월', desc: '은행, PB, 자산관리 직무를 목표로 할 때 강한 금융 자격입니다.', url: 'https://www.fpsbkorea.org/' },
  { id: 'credit-analyst', title: '신용분석사', cat: 'cert', type: 'certificate', tags: [W.FINANCE, W.ACCOUNTING, W.CERTIFICATE], baseWeight: 8, recommendedGrades: [3, 4], source: '한국금융연수원', targetDate: '2026-06-13', duration: '2~3개월', desc: '기업금융, 여신, 리스크 직무의 재무 분석 역량을 보여줍니다.', url: 'https://www.kbi.or.kr/' },
  { id: 'cpa-credit', title: 'CPA 응시 학점 요건', cat: 'cert', type: 'certificate', tags: [W.ACCOUNTING, W.FINANCE, W.CERTIFICATE], baseWeight: 9, recommendedGrades: [1, 2], source: '금융감독원', targetDate: '2026-12-31', duration: '학기 중', desc: '회계사 준비를 시작한다면 회계, 경영, 경제 학점 요건을 먼저 맞춰야 합니다.', url: 'https://cpa.fss.or.kr/' },
  { id: 'leet', title: 'LEET', cat: 'project', type: 'exam', tags: [W.LAW, W.LANGUAGE, W.PROJECT], baseWeight: 9, recommendedGrades: [3, 4], source: '법학적성시험', targetDate: '2026-07-19', duration: '6개월+', desc: '로스쿨 입시의 핵심 평가로 언어이해와 추리논증 훈련이 필요합니다.', url: 'https://leet.uwayapply.com/' },
  { id: 'mechanical-engineer', title: '일반기계기사', cat: 'cert', type: 'certificate', tags: [W.ENGINEERING, W.CERTIFICATE], baseWeight: 8, recommendedGrades: [3, 4], source: 'Q-Net', targetDate: '2026-07-05', duration: '2~4개월', desc: '기계, 생산, 설비 직무의 전공 기반을 증명하는 대표 기사 자격입니다.', url: 'https://www.q-net.or.kr/' },
  { id: 'electric-engineer', title: '전기기사', cat: 'cert', type: 'certificate', tags: [W.ENGINEERING, W.ENERGY, W.CERTIFICATE], baseWeight: 8, recommendedGrades: [3, 4], source: 'Q-Net', targetDate: '2026-07-05', duration: '2~4개월', desc: '전기, 설비, 에너지, 공기업 기술직을 준비할 때 활용도가 높습니다.', url: 'https://www.q-net.or.kr/' },
  { id: 'food-engineer', title: '식품기사', cat: 'cert', type: 'certificate', tags: [W.FOOD, W.BIO, W.CERTIFICATE], baseWeight: 8, recommendedGrades: [3, 4], source: 'Q-Net', targetDate: '2026-07-05', duration: '2~3개월', desc: '식품 연구개발, 품질관리, 생산관리 직무에 직접 연결되는 자격입니다.', url: 'https://www.q-net.or.kr/' },
  { id: 'nutritionist', title: '영양사', cat: 'cert', type: 'certificate', tags: [W.FOOD, W.BIO, W.CERTIFICATE], baseWeight: 8, recommendedGrades: [3, 4], source: '한국보건의료인국가시험원', targetDate: '2026-11-20', duration: '학기 중', desc: '식품영양 및 보건 계열에서 면허 기반 진로를 만들 수 있습니다.', url: 'https://www.kuksiwon.or.kr/' },
  { id: 'fashion-md', title: '패션머천다이징산업기사', cat: 'cert', type: 'certificate', tags: [W.DESIGN, W.MARKETING, W.CERTIFICATE], baseWeight: 7, recommendedGrades: [2, 3], source: 'Q-Net', targetDate: '2026-07-05', duration: '2개월', desc: '패션 MD, 브랜드 기획, 상품 기획 진로에 전공성과 시장 감각을 더합니다.', url: 'https://www.q-net.or.kr/' },
  { id: 'gtq', title: 'GTQ', cat: 'cert', type: 'certificate', tags: [W.DESIGN, W.CONTENTS, W.CERTIFICATE], baseWeight: 6, recommendedGrades: [1, 2], source: 'KPC 자격', targetDate: '2026-06-20', duration: '1개월', desc: '디자인과 콘텐츠 제작 직무에서 기본 그래픽 툴 활용도를 보여줍니다.', url: 'https://license.kpc.or.kr/' },
  { id: 'sopt', title: 'IT 연합동아리 SOPT/NEXTERS', cat: 'activity', type: 'activity', tags: [W.SOFTWARE, W.UX, W.PROJECT, W.ACTIVITY], baseWeight: 8, recommendedGrades: [1, 2, 3], source: '캠퍼스픽', targetDate: '2026-09-01', duration: '한 학기', desc: '개발, 기획, 디자인 협업 프로젝트 경험을 빠르게 쌓을 수 있습니다.', url: 'https://sopt.org/' },
  { id: 'boostcamp', title: '부스트캠프/우아한테크코스', cat: 'project', type: 'project', tags: [W.SOFTWARE, W.PROJECT, W.INTERNSHIP], baseWeight: 9, recommendedGrades: [3, 4], source: '교육 프로그램', targetDate: '2026-06-10', duration: '3~6개월', desc: '개발 실무와 포트폴리오를 동시에 강화하는 고강도 프로젝트 프로그램입니다.', url: 'https://woowacourse.github.io/' },
  { id: 'hackathon', title: '해커톤/서비스 제작 공모전', cat: 'project', type: 'competition', tags: [W.SOFTWARE, W.AI, W.UX, W.COMPETITION, W.PROJECT], baseWeight: 7, recommendedGrades: [2, 3], source: '링커리어', targetDate: '2026-09-15', duration: '단기', desc: '짧은 기간 안에 문제정의, 구현, 발표 경험을 만들 수 있습니다.', url: 'https://linkareer.com/' },
  { id: 'marketing-school', title: 'KT&G 상상유니브 마케팅스쿨', cat: 'activity', type: 'activity', tags: [W.MARKETING, W.CONTENTS, W.ACTIVITY], baseWeight: 7, recommendedGrades: [2, 3], source: '상상유니브', targetDate: '2026-07-20', duration: '단기', desc: '마케팅 실무와 캠페인 기획 경험을 쌓기 좋은 대외활동입니다.', url: 'https://www.sangsanguniv.com/' },
  { id: 'cheil', title: '제일기획 아이디어 페스티벌', cat: 'project', type: 'competition', tags: [W.MARKETING, W.CONTENTS, W.MEDIA, W.COMPETITION], baseWeight: 8, recommendedGrades: [2, 3], source: '제일기획', targetDate: '2026-05-31', duration: '1~2개월', desc: '광고, 마케팅, 콘텐츠 기획 역량을 포트폴리오로 남기기 좋습니다.', url: 'https://ideafestival.cheil.co.kr/' },
  { id: 'finance-club', title: '가치투자/금융 학회', cat: 'activity', type: 'activity', tags: [W.FINANCE, W.DATA, W.RESEARCH, W.ACTIVITY], baseWeight: 7, recommendedGrades: [1, 2, 3], source: '교내', targetDate: '2026-09-05', duration: '한 학기+', desc: '기업 분석, 리서치, 밸류에이션 경험을 쌓아 금융 직무와 연결합니다.', url: '#' },
  { id: 'bank-ambassador', title: '은행권 대학생 홍보대사', cat: 'activity', type: 'activity', tags: [W.FINANCE, W.MARKETING, W.ACTIVITY], baseWeight: 7, recommendedGrades: [2, 3], source: '각 은행', targetDate: '2026-07-01', duration: '한 학기', desc: '금융권 조직 이해와 고객 커뮤니케이션 경험을 동시에 만들 수 있습니다.', url: 'https://www.kbcampusstar.com/' },
  { id: 'semiconductor-practice', title: '반도체 공정실습', cat: 'activity', type: 'activity', tags: [W.SEMICONDUCTOR, W.ENGINEERING, W.INTERNSHIP], baseWeight: 8, recommendedGrades: [2, 3], source: 'SPTA/교내', targetDate: '2026-06-20', duration: '단기', desc: '반도체 직무에서 공정 이해와 장비 경험을 보여주는 강한 실무 스펙입니다.', url: 'https://spta.co.kr/' },
  { id: 'lab-intern', title: '학부 연구생/랩실 인턴', cat: 'intern', type: 'internship', tags: [W.RESEARCH, W.ENGINEERING, W.BIO, W.AI, W.INTERNSHIP], baseWeight: 8, recommendedGrades: [2, 3], source: '교내 연구실', targetDate: '2026-06-10', duration: '방학~학기', desc: '연구, R&D, 대학원 진학, 기술 직무에 모두 연결되는 실험/분석 경험입니다.', url: '#' },
  { id: 'ncs-intern', title: '공공기관 청년인턴', cat: 'intern', type: 'internship', tags: [W.PUBLIC, W.NCS, W.INTERNSHIP], baseWeight: 8, recommendedGrades: [3, 4], source: '잡알리오', targetDate: '2026-07-01', duration: '1~3개월', desc: '공기업과 공공기관 직무 이해도를 높이고 면접 소재를 확보합니다.', url: 'https://job.alio.go.kr/' },
  { id: 'public-supporters', title: '공공기관 서포터즈/기자단', cat: 'activity', type: 'activity', tags: [W.PUBLIC, W.MEDIA, W.CONTENTS, W.ACTIVITY], baseWeight: 6, recommendedGrades: [1, 2], source: '링커리어', targetDate: '2026-06-05', duration: '한 학기', desc: '공공기관 관심도와 콘텐츠 제작 경험을 함께 보여줄 수 있습니다.', url: 'https://linkareer.com/' },
  { id: 'law-volunteer', title: '장기 멘토링/공익 봉사', cat: 'activity', type: 'activity', tags: [W.LAW, W.PUBLIC, W.ACTIVITY], baseWeight: 7, recommendedGrades: [1, 2, 3], source: 'VMS', targetDate: '2026-06-30', duration: '장기', desc: '로스쿨과 공공 계열에서 공익성과 지속성을 보여주는 정성 경험입니다.', url: 'https://www.vms.or.kr/' },
  { id: 'legal-intern', title: '법률구조공단 실무 수습', cat: 'intern', type: 'internship', tags: [W.LAW, W.PUBLIC, W.INTERNSHIP], baseWeight: 8, recommendedGrades: [3, 4], source: '법률구조공단', targetDate: '2026-11-01', duration: '방학', desc: '법무 실무와 공익 경험을 함께 쌓을 수 있는 로스쿨 준비형 활동입니다.', url: 'https://www.klac.or.kr/' },
  { id: 'campus-media', title: '교내 학보사/방송국', cat: 'activity', type: 'activity', tags: [W.MEDIA, W.CONTENTS, W.LANGUAGE, W.ACTIVITY], baseWeight: 8, recommendedGrades: [1, 2], source: '교내', targetDate: '2026-09-05', duration: '1년+', desc: '취재, 기사 작성, 영상 제작 등 미디어 직무의 기본 실무를 경험합니다.', url: '#' },
  { id: 'content-portfolio', title: '콘텐츠 포트폴리오 채널 운영', cat: 'project', type: 'project', tags: [W.CONTENTS, W.MEDIA, W.MARKETING, W.PROJECT], baseWeight: 7, recommendedGrades: [1, 2, 3], source: '개인 프로젝트', targetDate: '2026-09-01', duration: '상시', desc: '블로그, 뉴스레터, 영상 채널로 결과물을 꾸준히 축적합니다.', url: '#' },
  { id: 'design-portfolio', title: '디자인 포트폴리오 프로젝트', cat: 'project', type: 'project', tags: [W.DESIGN, W.UX, W.CONTENTS, W.PROJECT], baseWeight: 8, recommendedGrades: [2, 3, 4], source: '개인/팀 프로젝트', targetDate: '2026-09-01', duration: '상시', desc: '디자인 직무 지원에 필요한 문제정의, 시안, 결과물을 한 번에 정리합니다.', url: '#' },
  { id: 'fashion-supporters', title: '패션 브랜드 대외활동/앰버서더', cat: 'activity', type: 'activity', tags: [W.DESIGN, W.MARKETING, W.CONTENTS, W.ACTIVITY], baseWeight: 7, recommendedGrades: [1, 2, 3], source: '캠퍼스픽', targetDate: '2026-05-30', duration: '한 학기', desc: '브랜드 감각과 소비자 커뮤니케이션 경험을 패션 직무와 연결합니다.', url: 'https://www.campuspick.com/' },
  { id: 'food-supporters', title: '식품/외식기업 서포터즈', cat: 'activity', type: 'activity', tags: [W.FOOD, W.MARKETING, W.ACTIVITY], baseWeight: 7, recommendedGrades: [1, 2, 3], source: '위비티', targetDate: '2026-06-05', duration: '한 학기', desc: '식품 기업과 소비자 관점을 함께 이해할 수 있는 활동입니다.', url: 'https://www.wevity.com/' },
  { id: 'hy-wep', title: '한양대학교 현장실습(HY-WEP)', cat: 'intern', type: 'internship', tags: [W.INTERNSHIP, W.PROJECT, W.MANAGEMENT], baseWeight: 7, recommendedGrades: [3, 4], source: 'HY-in 포털', targetDate: '2026-06-10', duration: '방학~학기', desc: '학교와 연계된 기업 실무 경험으로 대부분의 직무에 활용할 수 있습니다.', url: 'https://portal.hanyang.ac.kr/' },
];
